EXTENSION   = chess_extension
MODULES     = chess_extension
DATA        = chess_extension--1.0.sql chess_extension.control

PG_CONFIG ?= pg_config
PGXS = $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
